### ISSUE TITLE
laterjoin - a whole bunch of weird bugs and errors 05.09.2019

### ISSUE THREAD

**Issue by Tamago4a** [storm37000/SCPSL_Smod_LaterJoin#12]
https://www.youtube.com/watch?v=70EnElB6u8E
OPEN DESCRIPTION 
minimum_MTF_time_to_spawn: 150
maximum_MTF_time_to_spawn: 300
ci_respawn_percent: 50
team_respawn_queue: 0434434441043414404341134
filler_team_id: 4
auto_warhead_start_lock: true
lj_FillerTeamQueue: 4,4,4,3,4,4,4,3,1
lj_InfAutoRespawn: true
lj_InfAutoRespawn_delay: 5
lj_InfAutoRespawn_queue: 4,4,4,3,4,4,4,3,1

start_round_timer: 60(1 minute)
lj_time: 600(10 minutes)
decontamination_time: 10(600 seconds)
auto_warhead_start: 900(15 minutes)
seconds_until_force_restart: 1200(20 minutes)
auto_round_restart_time: 30(0,5 minute)

0:08 server configuration
2:50 a message that in 10 minutes the decontamination light zone event will be generated. It’s strange. This is probably a smod error. In any case, the event "auto_warhead_start: 900 (15 minutes)" will be played 15 minutes after the start of the match. In any case, if there are any errors in smod over time, the laterjoin plugin will work until the restart of the match.
4:58 player 155 AFTER DEATH got the role from the list "team_respawn_queue: 0434434441043414404341134". Don't you think this logic is pretty dumb? After all, a player has the right to get a role from this list only if he has not managed to enter the server. If a player dies, he must get a role from the list "lj_InfAutoRespawn_queue: 4,4,4,3,4,4,4,4,1,1".
5:45 test plug-in for resistance to stress. The test was successful. The result is positive.
5:54 - 6:49 can be skipped because a rendering error occurred. In any case, all the players got their roles.
10:12 two players(players numbered 153 and 158) who killed an ally can not get their roles.
10:58 two players(players numbered 153 and 158) who were killed by an ally got their roles due to the events "minimum_MTF_time_to_spawn: 150", "maximum_MTF_time_to_spawn: 300" and "ci_respawn_percent: 50".
11:40 player 153 killed player 158 (apparently by accident :) ). Friendly Fire Autoban plugin changed the role of surviving player 153 to spectator. Player 158 received the role, but player 153 did not. I think it should be so.
12:18 light zone cleared. The plugin continues to work and resurrect players.
12:56 player 158 killed player 165 and for that the Friendly Fire Autoban plugin changed his role on spectator. As a result, there are 2 spectators again.
13:38 plug-in stress test again.
13:54 a couple of spectators got their roles thanks to the events "minimum_MTF_time_to_spawn: 150", "maximum_MTF_time_to_spawn: 300" and "ci_respawn_percent: 50".
14:18 I turned off my overwatch mode. In theory, the plugin should see this and immediately give me the role.
14:42 the laterjoin plugin continues to work and infinitely resurrects the players for "CLASS # 015 - Facility Guard". Because of this role in the list below, they lose their meaning: "CLASS#004 - Nine-Tailed Fox Scientist", "CLASS#008 - Chaos Insurgency", "CLASS#011 - Nine-Tailed Fox Lieutenant", "CLASS#012 - Nine-Tailed Fox Commander" and "CLASS#013 - Nine-Tailed Fox Cadet".
15:20 I definitely know the logic of this plugin. I gave the role of spectator and he soon died. The player’s “death” event caused the plugin to work.
16:05 plug-in stress test again.
16:22 I gave the spectator role, but because of the lj_InfAutoRespawn_delay: 5 delay, the plugin didn’t see it and gave it the role on top of my role.
16:30 end of the match. The plugin breaks and again starts to resurrect everyone on the list for Class D and Scientists. And the strangest thing is, the plugin resurrects all the same players 153 and 158.

**Comment by storm37000** [comment]
ok, i think i know how to fix some of those issues.  The thing with Friendly Fire Autoban is an issue with how it is setting them to spectator, i suggest using `friendly_fire_autoban_mirror:2` instead of `friendly_fire_autoban_tospec`

**Comment by Tamago4a** [comment]
But the fact is that this is not the only mistake. I add that the setting "friendly_fire_autoban_mirror" does not work. There are many inconsistencies in this video with what is in the plugin description.
