### ISSUE TITLE
Plugin trying to respawn Player Server

### ISSUE THREAD

**Issue by PUDGE133** [storm37000/SCPSL_Smod_LaterJoin#7]
![Безымянный](https://user-images.githubusercontent.com/47304666/58747525-ef74e900-8474-11e9-8aeb-0feb26de1c0a.png)
![Безымянный](https://user-images.githubusercontent.com/47304666/58747526-f4d23380-8474-11e9-9d7a-3e8c928bfc59.png)

**Comment by storm37000** [comment]
working on fixing this in next release

**Comment by storm37000** [comment]
fixed
